### ISSUE TITLE
Error when accessing single entry section

### ISSUE THREAD

**Issue by twiro** [jensscherbl/singles#1]
Just gave this a try and received the following error-message after trying to access a section that was (successfully) saved as "single entry section":

    Symphony Fatal Error: Call to a member function getChild() on a non-object
    An error occurred in .../extensions/singles/extension.driver.php around line 182

PHP is 5.3, Symphony 2.5.2

**Comment by jensscherbl** [comment]
Sorry, my fault. Minimum requirement is the upcoming [Symphony 2.6.0][2] release. [extension.meta.xml][1] should be correct now.

[1]: https://github.com/jensscherbl/singles/blob/master/extension.meta.xml
[2]: https://github.com/symphonycms/symphony-2/milestones/2.6.0
